// packages/blog-nuxt/src/projects/components/FeaturedProjects/index.vue
<script setup lang="ts">
import type { ProjectModel } from '~/projects/utils/project.model';

const { data } = await useAsyncData(() =>
  queryContent<ProjectModel>('/projects').where({ isFeatured: true }).find(),
);
</script>

<template>
  <ProjectTiledGrid title="Featured Projects">
    <ProjectTiledGridCell
      v-for="project in data"
      :href="project._path"
      :status="project.status">
      <template v-slot:name>{{ project.name }}</template>
      <template v-slot:slogan>{{ project.slogan }}</template>
      <template v-slot:image>
        <ThemedImage
          :src="project.logo"
          alt="project logo"
          :srcDark="project.logoDark" />
      </template>
      <template v-slot:version>{{ project.version }}</template>
    </ProjectTiledGridCell>

    <ProjectTiledGridEmptyCell href="/projects">
      See all
    </ProjectTiledGridEmptyCell>
  </ProjectTiledGrid>
</template>

// packages/blog/src/projects/components/FeaturedProjects.tsx
import type { FC } from 'react';
import type { ProjectModel } from '../models/project.model.js';
import { ProjectTiledGrid } from './ProjectTiledGrid.js';
import { ProjectTiledGridCell } from './ProjectTiledGridCell.js';
import { ProjectTiledGridEmptyCell } from './ProjectTiledGridEmptyCell.js';

export const FeaturedProjects: FC<FeaturedProjectsProps> = function ({
  projects,
}) {
  return (
    <ProjectTiledGrid title={`Featured Projects`}>
      {projects.map((project) => (
        <ProjectTiledGridCell
          project={project}
          key={project.id}
        />
      ))}

      <ProjectTiledGridEmptyCell href="/projects">
        See all
      </ProjectTiledGridEmptyCell>
    </ProjectTiledGrid>
  );
};

export interface FeaturedProjectsProps {
  projects: ProjectModel[];
}
