// packages/blog/src/components/ProjectChangelogs.tsx
import {
  getChangelogFullPath,
  type Changelog,
} from '@/shared/changelog.helpers.ts';
import {
  PublishedAtFormat,
  formatEntryPublishedAt,
} from '@/shared/collection.helpers.ts';
import type { FunctionComponent } from 'react';
import { ArchiveList } from './ArchiveList/ArchiveList.tsx';
import { ArchiveListItem } from './ArchiveList/ArchiveListItem.tsx';

export const ProjectChangelogs: FunctionComponent<ProjectChangelogsProps> =
  function ({ changelogs }) {
    return (
      <ArchiveList>
        {changelogs.map((changelog) => (
          <ArchiveListItem
            left={`v${changelog.data.version}`}
            right={formatEntryPublishedAt(
              changelog.data.publishedAt,
              PublishedAtFormat.SHORT,
            )}
            href={getChangelogFullPath(changelog)}
          />
        ))}
      </ArchiveList>
    );
  };

export interface ProjectChangelogsProps {
  changelogs: Changelog[];
}

// packages/blog-nuxt/src/projects/components/ProjectChangelogs/index.vue
<script setup lang="ts">
import type { ChangelogModel } from '~/projects/utils/changelog.model';
import { format } from 'date-fns';
import { PublishedAtFormat } from '~/utils/published-at-format';

const props = defineProps<{ slug: string }>();

const { data } = await useAsyncData(() =>
  queryContent<ChangelogModel>(`/projects/${props.slug}/changelogs`)
    .sort({ publishedAt: -1 })
    .find(),
);
</script>

<template>
  <ArchiveList title="Changelogs">
    <ArchiveListItem
      v-for="changelog in data"
      :href="changelog._path">
      <template v-slot:left>v{{ changelog.version }}</template>
      <template v-slot:right>
        {{ format(changelog.publishedAt, PublishedAtFormat.SHORT) }}
      </template>
    </ArchiveListItem>
  </ArchiveList>
</template>
