// packages/blog/src/projects/components/project-changelogs.tsx
import { format } from "date-fns";
import type { FC } from "react";
import { ArchiveListItem } from "../../ui/components/archive-list-item.js";
import { ArchiveList } from "../../ui/components/archive-list.js";
import type { ChangelogModel } from "../models/changelog.model.js";
import { publishedAtFormat } from "../../content/globals/published-at-format.js";

export const ProjectChangelogs: FC<ProjectChangelogsProps> = ({
	changelogs,
}) => (
	<ArchiveList title={"Changelogs"}>
		{changelogs.map((changelog) => (
			<ArchiveListItem
				key={changelog.id}
				left={changelog.matter.version}
				right={format(changelog.matter.publishedAt, publishedAtFormat.short)}
				href={changelog.path}
			/>
		))}
	</ArchiveList>
);

export interface ProjectChangelogsProps {
	changelogs: ChangelogModel[];
}

// packages/blog-nuxt/src/projects/components/ProjectChangelogs/index.vue
<script setup lang="ts">
import type { ChangelogModel } from '~/projects/utils/changelog.model';
import { format } from 'date-fns';
import { PublishedAtFormat } from '~/utils/published-at-format';

const props = defineProps<{ slug: string }>();

const { data } = await useAsyncData(() =>
  queryContent<ChangelogModel>(`/projects/${props.slug}/changelogs`)
    .sort({ publishedAt: -1 })
    .find(),
);
</script>

<template>
  <ArchiveList title="Changelogs">
    <ArchiveListItem
      v-for="changelog in data"
      :href="changelog._path">
      <template v-slot:left>v{{ changelog.version }}</template>
      <template v-slot:right>
        {{ format(changelog.publishedAt, PublishedAtFormat.SHORT) }}
      </template>
    </ArchiveListItem>
  </ArchiveList>
</template>
