// packages/canvas/src/Home/index.vue
<script setup lang="ts">
import { routeToName } from '@/Home/index.meta.ts';
import CenteredLayout from '@/shared/layouts/CenteredLayout/index.vue';
</script>

<template>
  <CenteredLayout>
    <nav>
      <ul>
        <li v-for="name in Object.values(routeToName)">
          <router-link
            :to="{ name }"
            class="text-slate-500 hover:text-cyan-500">
            {{ name }}
          </router-link>
        </li>
      </ul>
    </nav>
  </CenteredLayout>
</template>

// packages/canvas/src/Home/Home.tsx
import { Layout } from '@/shared/Layout.tsx';
import { routeToLabel } from '@/shared/route.ts';
import { cn } from '@digital-garden/utils';
import type { FunctionComponent } from 'react';
import { Link } from 'react-router-dom';

export const Home: FunctionComponent = function () {
  return (
    <Layout>
      <nav>
        <ul>
          {Object.entries(routeToLabel).map(([link, label]) => (
            <li key={link}>
              <Link
                to={link}
                className={cn('text-slate-500 hover:text-cyan-500')}>
                {label}
              </Link>
            </li>
          ))}
        </ul>
      </nav>
    </Layout>
  );
};
