// packages/blog/src/components/PinnedPosts.tsx
import {
  PublishedAtFormat,
  formatEntryPublishedAt,
} from '@/shared/collection.helpers.ts';
import { getPostFullPath, type Post } from '@/shared/post.helpers.ts';
import type { FunctionComponent } from 'react';
import { ArchiveListItem } from './ArchiveList/ArchiveListItem.tsx';
import { StandOut } from './StandOut.tsx';

export const PinnedPosts: FunctionComponent<PinnedPostsProps> = function ({
  posts,
}) {
  return (
    <>
      <ul>
        {posts.map((post) => (
          <StandOut
            className="flex-col"
            key={post.id}>
            <span className="flex gap-3 items-center">
              <span className="-scale-x-100">📌</span>

              <ArchiveListItem
                left={post.data.title}
                right={formatEntryPublishedAt(
                  post.data.publishedAt,
                  PublishedAtFormat.SHORT,
                )}
                href={getPostFullPath(post)}
                className="flex-1 !py-0"
              />
            </span>
          </StandOut>
        ))}
      </ul>
    </>
  );
};

export interface PinnedPostsProps {
  posts: Post[];
}

// packages/blog-nuxt/posts/components/PinnedPosts/index.vue
<script setup lang="ts">
import type { PostModel } from '~/posts/utils/post.model';
import { format } from 'date-fns';
import { PublishedAtFormat } from '~/utils/published-at-format';

const { data } = await useAsyncData(() =>
  queryContent<PostModel>('/posts')
    .where({ isPinned: true })
    .sort({ publishedAt: -1 })
    .find(),
);
</script>

<template>
  <menu>
    <StandOut
      v-for="post in data"
      class="flex-col">
      <span class="flex gap-3 items-center">
        <span class="-scale-x-100">📌</span>

        <ArchiveListItem
          :href="post._path"
          class="flex-1 !py-0">
          <template v-slot:left>{{ post.title }}</template>
          <template v-slot:right>
            {{ format(post.publishedAt, PublishedAtFormat.SHORT) }}
          </template>
        </ArchiveListItem>
      </span>
    </StandOut>
  </menu>
</template>
