// packages/blog/src/posts/components/pinned-posts.tsx
import { format } from "date-fns";
import type { FC } from "react";
import { ArchiveListItem } from "../../ui/components/archive-list-item.js";
import { StandOut } from "../../ui/components/stand-out.js";
import { cn } from "../../ui/utils/cn.js";
import type { PostModel } from "../models/post.model.js";
import { publishedAtFormat } from "../../content/globals/published-at-format.js";

export const PinnedPosts: FC<PinnedPostsProps> = ({ posts }) => (
	<menu>
		{posts.map((post) => (
			<StandOut
				className="flex-col"
				key={post.id}
			>
				<span className="flex gap-3 items-center">
					<span className="-scale-x-100">📌</span>

					<ArchiveListItem
						left={post.matter.title}
						right={format(post.matter.publishedAt, publishedAtFormat.short)}
						href={post.path}
						className={cn("flex-1 !py-0")}
					/>
				</span>
			</StandOut>
		))}
	</menu>
);

export interface PinnedPostsProps {
	posts: PostModel[];
}

// packages/blog-nuxt/posts/components/PinnedPosts/index.vue
<script setup lang="ts">
import type { PostModel } from '~/posts/utils/post.model';
import { format } from 'date-fns';
import { PublishedAtFormat } from '~/utils/published-at-format';

const { data } = await useAsyncData(() =>
  queryContent<PostModel>('/posts')
    .where({ isPinned: true })
    .sort({ publishedAt: -1 })
    .find(),
);
</script>

<template>
  <menu>
    <StandOut
      v-for="post in data"
      class="flex-col">
      <span class="flex gap-3 items-center">
        <span class="-scale-x-100">📌</span>

        <ArchiveListItem
          :href="post._path"
          class="flex-1 !py-0">
          <template v-slot:left>{{ post.title }}</template>
          <template v-slot:right>
            {{ format(post.publishedAt, PublishedAtFormat.SHORT) }}
          </template>
        </ArchiveListItem>
      </span>
    </StandOut>
  </menu>
</template>
