// packages/blog-nuxt/src/ui/components/Header/index.vue
<script setup lang="ts">
import HeaderLogo from '~/ui/assets/img/header-logo.webp';
import HeaderLogoDark from '~/ui/assets/img/header-logo-dark.webp';
</script>

<template>
  <header
    class="flex gap-1 items-center p-4 border-b border-slate-300 dark:border-slate-600">
    <nav>
      <ButtonLink
        class="!p-0"
        href="/">
        <ThemedImage
          :src="HeaderLogo"
          :srcDark="HeaderLogoDark"
          alt="Logo"
          width="120" />
      </ButtonLink>
    </nav>

    <div class="flex-1"></div>

    <slot />
  </header>
</template>

// packages/blog/src/layouts/MainLayout/Header/index.tsx
import { ButtonLink } from '@/components/ButtonLink';
import { ThemedImage } from '@/components/ThemedImage';
import { cn } from '@/shared/react.helpers';
import { THEME } from '@/shared/theme';
import type { FunctionComponent, PropsWithChildren } from 'react';
import HeaderLogo from './HeaderLogo.webp?url';
import HeaderLogoDark from './HeaderLogoDark.webp?url';

export const Header: FunctionComponent<PropsWithChildren<HeaderProps>> =
  function ({ children }) {
    return (
      <header
        className={cn('flex gap-1 items-center p-4 border-b', ...THEME.border)}>
        <nav>
          <ButtonLink
            href="/"
            className={cn('!p-0')}>
            <ThemedImage
              src={HeaderLogo}
              srcDark={HeaderLogoDark}
              alt="Logo"
              width="120"
            />
          </ButtonLink>
        </nav>

        <span className="flex-1"></span>

        {children}
      </header>
    );
  };

export interface HeaderProps {}
