// packages/blog/src/projects/components/featured-projects.tsx
import type { FC } from "react";
import type { ProjectModel } from "../models/project.model.js";
import { ProjectTiledGridCell } from "./project-tiled-grid-cell.js";
import { ProjectTiledGridEmptyCell } from "./project-tiled-grid-empty-cell.js";
import { ProjectTiledGrid } from "./project-tiled-grid.js";

export const FeaturedProjects: FC<FeaturedProjectsProps> = ({ projects }) => (
	<ProjectTiledGrid title={"Featured Projects"}>
		{projects.map((project) => (
			<ProjectTiledGridCell
				project={project}
				key={project.id}
			/>
		))}

		<ProjectTiledGridEmptyCell href="/projects">
			See all
		</ProjectTiledGridEmptyCell>
	</ProjectTiledGrid>
);

export interface FeaturedProjectsProps {
	projects: ProjectModel[];
}

// packages/blog-nuxt/projects/components/FeaturedProjects/index.vue
<script setup lang="ts">
import type { ProjectModel } from '~/projects/utils/project.model';

const { data } = await useAsyncData(() =>
  queryContent<ProjectModel>('/projects').where({ isFeatured: true }).find(),
);
</script>

<template>
  <ProjectTiledGrid title="Featured Projects">
    <ProjectTiledGridCell
      v-for="project in data"
      :project="project" />

    <ProjectTiledGridEmptyCell href="/projects">
      See all
    </ProjectTiledGridEmptyCell>
  </ProjectTiledGrid>
</template>
