// packages/blog-nuxt/src/projects/components/ProjectTiledList/Item.vue
<script setup lang="ts">
import type { ProjectModel } from '~/projects/utils/project.model';
import { compareDesc } from 'date-fns';
import type { ChangelogModel } from '~/projects/utils/changelog.model';

const props = defineProps<{ project: ProjectModel }>();

const { data } = useAsyncData(() =>
  queryContent<ChangelogModel>(`${props.project._path}/changelogs`).find(),
);

const changelogs = computed(() =>
  data
    .value!.toSorted((a, b) => compareDesc(a.publishedAt, b.publishedAt))
    .slice(0, 2),
);
</script>

<template>
  <Card
    :style="{
      '--bg-image-url': `url(${project.logo})`,
      '--bg-image-dark-url': `url(${project.logoDark})`,
    }"
    class="flex-1 flex-col bg-[image:var(--bg-image-url)] dark:bg-[image:var(--bg-image-dark-url)] bg-right bg-no-repeat bg-[length:auto_200%]">
    <CardOverlay
      class="bg-gradient-to-l from-transparent to-60% to-slate-50 dark:to-slate-900" />

    <div class="flex gap-2 items-center z-10">
      <AppLink :href="project._path">
        <AppTitle
          base="h6"
          class="hover:text-inherit">
          {{ project.name }}
        </AppTitle>
      </AppLink>
      <span>•</span>
      <Version
        :status="project.status"
        showStatus>
        {{ project.version }}
      </Version>
    </div>

    <Caption class="z-10">{{ project.slogan }}</Caption>

    <div class="grid grid-cols-2 z-10">
      <div class="flex flex-col">
        <Divider :isLeft="false">
          <Text base="span">Latest Changes</Text>
        </Divider>

        <menu class="flex flex-col divide-y divide-dashed">
          <li
            v-for="changelog in changelogs"
            class="flex flex-col py-1">
            <AppLink
              level="sm"
              :href="changelog._path">
              v{{ changelog.version }}
            </AppLink>
          </li>
        </menu>
      </div>

      <div class="flex flex-col gap-2 items-end justify-end self-end">
        <ButtonLink
          v-if="project.productionUrl"
          size="sm"
          target="_blank"
          :href="project.productionUrl"
          variant="outlined"
          class="bg-slate-50 dark:bg-slate-900 p-2 flex gap-1.5 items-center">
          <Icon glyph="globe" />
          Production
        </ButtonLink>

        <ButtonLink
          size="sm"
          target="_blank"
          :href="project.sourceCodeUrl"
          variant="outlined"
          class="bg-slate-50 dark:bg-slate-900 p-2 flex gap-1.5 items-center">
          <Icon glyph="github" />
          Source
        </ButtonLink>
      </div>
    </div>
  </Card>
</template>

// packages/blog/src/components/ProjectTiledList/Item.tsx
import {
  getChangelogFullPath,
  type Changelog,
} from '@/shared/changelog.helpers';
import {
  PublishedAtFormat,
  formatPublishedAt,
} from '@/shared/collection.helpers';
import {
  getProjectFullPath,
  isProjectDataWithCover,
  projectStatusToBadgeColor,
  projectStatusToLabel,
  type Project,
} from '@/shared/project.helpers';
import { cn } from '@/shared/react.helpers';
import { theme } from '@/shared/tailwind.helpers';
import type { FunctionComponent } from 'react';
import { Badge } from '../Badge';
import { ButtonLink } from '../ButtonLink';
import { Caption } from '../Caption';
import { Card } from '../Card';
import { Divider } from '../Divider';
import { Icon } from '../Icon';
import { Link } from '../Link';
import { Text } from '../Text';
import { Title } from '../Title';

export const Item: ItemComponent = function ({ project, changelogs }) {
  const { data } = project;
  return (
    <Card
      style={
        isProjectDataWithCover(data)
          ? {
              '--bg-image-url': `url(${data.coverImage.src})`,
              '--bg-image-dark-url': `url(${data.coverImageDark?.src})`,
            }
          : {}
      }
      className={cn(
        'flex-1 flex-col',
        'bg-[image:var(--bg-image-url)] bg-right bg-no-repeat bg-[length:auto_200%]',
      )}
      overlay={
        <Card.Overlay
          className={cn(
            'bg-gradient-to-l from-transparent to-60% to-slate-50 dark:to-slate-900',
          )}
        />
      }>
      <div className="flex gap-2 items-center">
        <Link href={getProjectFullPath(project)}>
          <Title className={cn('hover:text-inherit')}>{data.name}</Title>
        </Link>
        <span>•</span>
        <Badge color={projectStatusToBadgeColor[data.status]}>
          {projectStatusToLabel[data.status]}
        </Badge>
      </div>

      <Caption>{data.slogan}</Caption>

      <div className="grid grid-cols-2">
        <div className="flex flex-col">
          <Divider isLeft={false}>
            <Text>Latest Changes</Text>
          </Divider>
          <ul className={cn('flex flex-col divide-y divide-dashed')}>
            {changelogs.map((changelog) => (
              <li className={cn('flex flex-col py-1')}>
                <Link
                  level="sm"
                  href={getChangelogFullPath(changelog)}>
                  {formatPublishedAt(
                    changelog.data.publishedAt,
                    PublishedAtFormat.FULL,
                  )}
                </Link>
              </li>
            ))}
          </ul>
        </div>

        <div className="flex flex-col gap-2 items-end justify-end self-end">
          {data.productionUrl && (
            <ButtonLink
              level="sm"
              target="_blank"
              href={data.productionUrl}
              isOutlined={true}
              className={cn('p-2 flex gap-1.5 items-center', theme.background)}>
              <Icon glyph="globe" />
              Production
            </ButtonLink>
          )}

          <ButtonLink
            level="sm"
            target="_blank"
            href={data.sourceCodeUrl}
            isOutlined={true}
            className={cn('p-2 flex gap-1.5 items-center', theme.background)}>
            <Icon glyph="github" />
            Source
          </ButtonLink>
        </div>
      </div>
    </Card>
  );
};

export type ItemComponent = FunctionComponent<ItemProps>;

export interface ItemProps {
  project: Project;
  changelogs: Changelog[];
}
