// packages/blog-ssg/src/ui/components/themed-image/index.tsx
import type { ComponentPropsWithoutRef, FC } from 'react';

// in some cases you must set both height and width or prefer width over height because of this tailwindcss default
// https://github.com/tailwindlabs/tailwindcss/issues/506
export const ThemedImage: FC<ThemedImageProps> = function ({
  src,
  srcDark,
  ...rest
}) {
  return (
    <picture>
      {srcDark && (
        <source
          srcSet={srcDark}
          media="(prefers-color-scheme:dark)"
        />
      )}
      <img
        src={src}
        {...rest}
      />
    </picture>
  );
};

export interface ThemedImageProps extends ComponentPropsWithoutRef<'img'> {
  srcDark?: string;
}

// packages/blog-nuxt/ui/components/ThemedImage/index.vue
<script setup lang="ts">
defineProps<{
  src: string; // to make it required
  srcDark?: string;
}>();
</script>

<template>
  <picture>
    <source
      v-if="srcDark"
      :srcset="srcDark"
      media="(prefers-color-scheme:dark)" />
    <img
      :src="src"
      v-bind="$attrs" />
  </picture>
</template>
