// packages/canvas/src/DigitalGarden/index.vue
<script setup lang="ts">
import dark from './dark.png';
import light from './light.png';
import CenteredLayout from '@/shared/layouts/CenteredLayout/index.vue';
</script>

<template>
  <CenteredLayout>
    <div class="relative w-dvw h-dvh">
      <img
        :src="dark"
        class="absolute top-0 left-0 w-full h-full" />
      <img
        :src="light"
        class="light absolute top-0 left-0 w-full h-full" />
    </div>
  </CenteredLayout>
</template>

<style scoped>
.light {
  clip-path: polygon(0 0, 0 0, 100% 100%, 0 100%);
}
</style>

// packages/canvas/src/DigitalGarden/index.tsx
import clsx from 'clsx';
import type { FC } from 'react';
import dark from './dark.png';
import styles from './index.module.css';
import light from './light.png';

export const DigitalGarden: FC = function () {
  return (
    <div className="relative w-dvw h-dvh">
      <img
        src={dark}
        alt=""
        className="absolute top-0 left-0 w-full h-full"
      />
      <img
        src={light}
        alt=""
        className={clsx(
          styles.light,
          `light absolute top-0 left-0 w-full h-full`,
        )}
      />
    </div>
  );
};
