// packages/blog-nuxt/src/posts/components/PinnedPosts/index.vue
<script setup lang="ts">
import type { PostModel } from '~/posts/utils/post.model';
import { compareDesc, format } from 'date-fns';
import { PublishedAtFormat } from '~/utils/published-at-format';

const { data } = await useAsyncData(() =>
  queryContent<PostModel>('/posts').where({ isPinned: true }).find(),
);

const sortedPosts = computed(() =>
  data.value!.toSorted((a, b) => compareDesc(a.publishedAt, b.publishedAt)),
);
</script>

<template>
  <ul>
    <StandOut
      v-for="post in sortedPosts"
      class="flex-col">
      <span class="flex gap-3 items-center">
        <span class="-scale-x-100">📌</span>

        <ArchiveListItem
          :href="post._path"
          class="flex-1 !py-0">
          <template v-slot:left>{{ post.title }}</template>
          <template v-slot:right>
            {{ format(post.publishedAt, PublishedAtFormat.SHORT) }}
          </template>
        </ArchiveListItem>
      </span>
    </StandOut>
  </ul>
</template>

// packages/blog/src/posts/components/PinnedPosts.tsx
import { format } from 'date-fns';
import type { FC } from 'react';
import { PublishedAtFormat } from '../../content/index.js';
import { ArchiveListItem, cn, StandOut } from '../../ui/index.js';
import { type PostModel } from '../models/post.model.js';

export const PinnedPosts: FC<PinnedPostsProps> = function ({ posts }) {
  return (
    <menu>
      {posts.map((post) => (
        <StandOut
          className="flex-col"
          key={post.id}>
          <span className="flex gap-3 items-center">
            <span className="-scale-x-100">📌</span>

            <ArchiveListItem
              left={post.matter.title}
              right={format(post.matter.publishedAt, PublishedAtFormat.SHORT)}
              href={post.path}
              className={cn(`flex-1 !py-0`)}
            />
          </span>
        </StandOut>
      ))}
    </menu>
  );
};

export interface PinnedPostsProps {
  posts: PostModel[];
}
