// packages/blog-nuxt/src/posts/components/RecentPosts/index.vue
<script setup lang="ts">
import type { PostModel } from '~/posts/utils/post.model';

const { data } = await useAsyncData(() =>
  queryContent<PostModel>('/posts').sort({ publishedAt: -1 }).limit(3).find(),
);
</script>

<template>
  <PostTiledList title="Recent Posts">
    <PostTiledListItem
      v-for="post in data"
      :post="post" />
  </PostTiledList>

  <AppLink
    class="self-center"
    href="/posts">
    See all
  </AppLink>
</template>

// packages/blog/src/posts/components/recent-posts.tsx
import type { FC } from "react";
import type { PostModel } from "../models/post.model.js";
import { PostTiledListEmptyItem } from "./post-tiled-list-empty-item.js";
import { PostTiledListItem } from "./post-tiled-list-item.js";
import { PostTiledList } from "./post-tiled-list.js";

export const RecentPosts: FC<RecentPostsProps> = ({ posts }) => (
	<PostTiledList title={"Recent Posts"}>
		{posts.map((post) => (
			<PostTiledListItem
				post={post}
				key={post.id}
			/>
		))}
		<PostTiledListEmptyItem href={"/posts"}>See all</PostTiledListEmptyItem>
	</PostTiledList>
);

export interface RecentPostsProps {
	posts: PostModel[];
}
