// packages/blog/src/components/PostList/Item.tsx
import {
  PublishedAtFormat,
  formatPostPublishedAt,
  getPostFullPath,
  type Post,
} from '@/shared/post.helpers';
import { cn } from '@/shared/react.helpers';
import { THEME } from '@/shared/theme';
import type { ComponentPropsWithoutRef, FunctionComponent } from 'react';
import { Link } from '../Link';

export const Item: ItemComponent = function ({
  className,
  post,
  publishedAtFormat,
  ...rest
}) {
  return (
    <li
      className={cn('flex flex-col py-3 text-medium', className)}
      {...rest}>
      <Link
        href={getPostFullPath(post)}
        prefetch="hover"
        className={cn(...THEME.primaryText, 'flex gap-3 items-center')}
        aria-label={post.data.title}>
        <span className="flex-1 truncate">{post.data.title}</span>
        <span className="whitespace-nowrap text-xs">
          {formatPostPublishedAt(post, publishedAtFormat)}
        </span>
      </Link>
    </li>
  );
};

export type ItemComponent = FunctionComponent<ItemProps>;

export interface ItemProps extends ComponentPropsWithoutRef<'li'> {
  post: Post;
  publishedAtFormat?: PublishedAtFormat;
}

// packages/blog-nuxt/ui/components/ArchiveList/Item.vue
<script setup lang="ts">
defineProps<{ href: string }>();
</script>

<template>
  <li class="flex flex-col py-3 text-medium">
    <AppLink
      class="text-slate-800 dark:text-slate-100 flex gap-3 items-center"
      :href="href">
      <span class="flex-1 truncate">
        <slot name="left" />
      </span>
      <span class="whitespace-nowrap text-xs">
        <slot name="right" />
      </span>
    </AppLink>
  </li>
</template>
