// packages/blog-nuxt/src/ui/components/Footer/index.vue
<template>
  <footer
    class="flex gap-1 items-center p-4 border-t border-slate-300 dark:border-slate-600 text-slate-500">
    <!-- TODO replace with Text -->
    <span class="text-sm">Mordechai Dror © 2023-present</span>

    <div class="flex-1"></div>

    <ButtonLink
      href="/rss.xml"
      aria-label="RSS feed"
      target="_blank">
      <Icon glyph="rss" />
    </ButtonLink>
  </footer>
</template>

// packages/blog/src/layouts/MainLayout/Footer.tsx
import { ButtonLink } from '@/components/ButtonLink';
import { Icon } from '@/components/Icon';
import { profile } from '@/shared/profile';
import { cn } from '@/shared/react.helpers';
import type { FunctionComponent } from 'react';

export const Footer: FunctionComponent<FooterProps> = function () {
  return (
    <footer
      className={cn(
        'flex gap-1 items-center p-4 border-t',
        'va-border va-secondary-text',
      )}>
      <span className="text-sm">{profile.copyright}</span>

      <div className="flex-1"></div>

      <ButtonLink
        href="/rss.xml"
        aria-label="RSS feed"
        target="_blank">
        <Icon glyph="rss" />
      </ButtonLink>
    </footer>
  );
};

export interface FooterProps {}
