// packages/blog-nuxt/src/ui/components/Modal/index.vue
<script setup lang="ts">
const mobileNav = useMobileNav();
const motions = useMotions();

function hideMobileNav() {
  mobileNav.value = false;
}
</script>

<template>
  <transition
    :css="false"
    @leave="(_, done) => motions.mobileNav.leave(done)">
    <div
      v-if="mobileNav"
      v-motion="'mobileNav'"
      :initial="{
        transform: 'translateY(-100%)',
      }"
      :enter="{ transform: 'translateY(0%)', transition: { duration: 300 } }"
      :leave="{ transform: 'translateY(-100%)', transition: { duration: 300 } }"
      class="fixed top-0 left-0 w-dvw h-dvh backdrop-filter backdrop-blur z-10">
      <div
        class="mx-auto sm:max-w-md md:max-w-lg lg:max-w-xl xl:max-w-2xl flex flex-col h-full">
        <Header>
          <Button
            aria-label="modal-close"
            @click="hideMobileNav()">
            <Icon glyph="close" />
          </Button>
        </Header>

        <slot />
      </div>
    </div>
  </transition>
</template>

// packages/blog/src/layouts/MainLayout/Modal.tsx
import { Button } from '@/components/Button/Button';
import { Icon } from '@/components/Icon';
import { cn } from '@/shared/react.helpers';
import { AnimatePresence, motion } from 'framer-motion';
import {
  useEffect,
  useState,
  type Dispatch,
  type FunctionComponent,
  type PropsWithChildren,
  type SetStateAction,
} from 'react';
import { Header } from './Header/Header';

export const Modal: FunctionComponent<PropsWithChildren<ModalProps>> =
  function ({ children, isOpen, onCloseClick }) {
    return (
      <AnimatePresence>
        {isOpen && (
          <motion.div
            key="modal"
            initial={{ y: '-100%' }}
            animate={{ y: '0' }}
            // for some reason works only with y, translateY on exit specifically causes loss of animation
            exit={{ y: '-100%' }}
            transition={{ duration: 0.3 }}
            className={cn(
              'fixed top-0 left-0 w-dvw h-dvh backdrop-filter backdrop-blur z-10',
            )}>
            <div className={cn('va-fullscreen flex flex-col h-full')}>
              <Header>
                <Button
                  aria-label="modal-close"
                  onClick={onCloseClick}>
                  <Icon glyph="close" />
                </Button>
              </Header>

              {children}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    );
  };

export function useIsModalOpen(): [boolean, Dispatch<SetStateAction<boolean>>] {
  const [isModalOpen, setIsModalOpen] = useState(false);

  useEffect(() => {
    document.body.style.overflow = isModalOpen ? 'hidden' : 'unset';
  }, [isModalOpen]);

  return [isModalOpen, setIsModalOpen];
}

export interface ModalProps {
  isOpen: boolean;
  onCloseClick(): void;
}
