// packages/blog/src/components/PostTiledList/Item.tsx
import {
  formatEntryPublishedAt,
  isEntryDataWithCover,
  PublishedAtFormat,
} from '@/shared/collection.helpers';
import { getPostFullPath, type Post } from '@/shared/post.helpers';
import { cn } from '@/shared/react.helpers';
import type { FunctionComponent } from 'react';
import { Caption } from '../Caption';
import { Link } from '../Link';
import { ThemedImage } from '../ThemedImage';
import { Title } from '../Title';

export const Item: ItemComponent = function ({ post, publishedAtFormat }) {
  const { data } = post;

  return (
    <li
      className={cn(
        'flex flex-col text-medium rounded-md duration-100',
        'hover:border hover:shadow-md hover:scale-105',
        'va-border',
      )}
      key={post.id}>
      <Link
        href={getPostFullPath(post)}
        prefetch="hover"
        className={cn('flex items-center p-3 group')}>
        <div className={cn('flex-1 overflow-hidden')}>
          <Title className={cn('truncate group-hover:text-inherit')}>
            {post.data.title}
          </Title>
          {/* this inline-block removes the inherited text-decoration, since it cannot be simply
          overridden like any other parent css style*/}
          <Caption className="inline-block">
            {formatEntryPublishedAt(data.publishedAt, publishedAtFormat)}
          </Caption>
        </div>
        {isEntryDataWithCover(data) && (
          <ThemedImage
            className="h-20 w-20 object-scale-down"
            src={data.coverImage.src}
            srcDark={data.coverImageDark?.src}
            alt={data.coverImageAlt!}
          />
        )}
      </Link>
    </li>
  );
};

export type ItemComponent = FunctionComponent<ItemProps>;

export interface ItemProps {
  post: Post;
  publishedAtFormat?: PublishedAtFormat;
}

// packages/blog-nuxt/src/posts/components/PostTiledList/Item.vue
<script setup lang="ts">
import type { PostModel } from '~/posts/utils/post.model';
import { format } from 'date-fns';

defineProps<{ post: PostModel }>();
</script>

<template>
  <li
    class="flex flex-col text-medium rounded-md duration-100 border border-transparent group cursor-pointer hover:border-slate-300 hover:dark:border-slate-600 hover:shadow-md hover:scale-105">
    <AppLink
      :href="post._path"
      class="flex items-center p-3">
      <!-- adding display: flex here breaks inline-block hack from below -->
      <div class="flex-1 overflow-hidden">
        <AppTitle
          base="h6"
          class="truncate group-hover:text-inherit">
          {{ post.title }}
        </AppTitle>
        <!-- this inline-block removes the inherited text-decoration, since it cannot be simply overridden like any other parent css style -->
        <Caption class="inline-block">
          {{ format(post.publishedAt, PublishedAtFormat.FULL) }}
        </Caption>
      </div>

      <div
        v-if="post.coverImage"
        class="h-20 w-20 object-scale-down flex items-center justify-center">
        <ThemedImage
          :src="post.coverImage"
          :alt="post.coverImageAlt"
          :srcDark="post.coverImageDark" />
      </div>
    </AppLink>
  </li>
</template>
