// packages/blog-ssg/src/ui/components/Divider.tsx
import { cn } from '@/core/cn.js';
import type { FC, PropsWithChildren } from 'react';

export const Divider: FC<PropsWithChildren<DividerProps>> = function ({
  isRight = true,
  isLeft = true,
  children,
}) {
  return (
    <div className="relative flex py-5 items-center">
      {isLeft && (
        <div
          className={cn(
            'border-slate-300 dark:border-slate-600 flex-grow border-t',
          )}
        />
      )}
      <div
        className={cn('flex-shrink', {
          'ml-4': isLeft,
          'mr-4': isRight,
        })}>
        {children}
      </div>
      {isRight && (
        <div
          className={cn(
            'border-slate-300 dark:border-slate-600 flex-grow border-t',
          )}
        />
      )}
    </div>
  );
};

export interface DividerProps {
  isLeft?: boolean;
  isRight?: boolean;
}

// packages/blog-nuxt/src/ui/components/Divider/index.vue
<script setup lang="ts">
withDefaults(defineProps<{ isLeft?: boolean; isRight?: boolean }>(), {
  isLeft: true,
  isRight: true,
});
</script>

<template>
  <div class="relative flex py-5 items-center">
    <div
      v-if="isLeft"
      class="border-slate-300 dark:border-slate-600 flex-grow border-t"></div>
    <div
      class="flex-shrink"
      :class="{
        'ml-4': isLeft,
        'mr-4': isRight,
      }">
      <slot />
    </div>
    <div
      v-if="isRight"
      class="border-slate-300 dark:border-slate-600 flex-grow border-t"></div>
  </div>
</template>
