// packages/canvas/src/DigitalGarden/DigitalGarden.tsx
import { Layout } from '@/shared/Layout.tsx';
import { cn } from '@digital-garden/utils';
import type { FunctionComponent } from 'react';
import styles from './DigitalGarden.module.css';
import dark from './dark.png';
import light from './light.png';

export const DigitalGarden: FunctionComponent = function () {
  return (
    <Layout>
      <div className={cn('relative w-dvw h-dvh')}>
        <img
          src={dark}
          className={cn('absolute top-0 left-0 w-full h-full')}
          alt=""
        />
        <img
          src={light}
          className={cn(styles.light, 'absolute top-0 left-0 w-full h-full')}
          alt=""
        />
      </div>
    </Layout>
  );
};

// packages/canvas/src/digital-garden/DigitalGarden.vue
<script setup lang="ts">
import { CenteredLayout } from '@digital-garden/components';
import dark from './dark.png';
import light from './light.png';
</script>

<template>
  <CenteredLayout>
    <div class="relative w-dvw h-dvh">
      <img
        :src="dark"
        class="absolute top-0 left-0 w-full h-full" />
      <img
        :src="light"
        class="light absolute top-0 left-0 w-full h-full" />
    </div>
  </CenteredLayout>
</template>

<style scoped>
.light {
  clip-path: polygon(0 0, 0 0, 100% 100%, 0 100%);
}
</style>
