// packages/blog-nuxt/src/posts/components/TiledList/Item.vue
<script setup lang="ts">
defineProps<{ href: string }>();
</script>

<template>
  <li
    class="flex flex-col text-medium rounded-md duration-100 border border-transparent group cursor-pointer hover:border-slate-300 hover:dark:border-slate-600 hover:shadow-md hover:scale-105">
    <AppLink
      :href="href"
      class="flex items-center p-3">
      <!-- adding display: flex here breaks inline-block hack from below -->
      <div class="flex-1 overflow-hidden">
        <AppTitle
          base="h6"
          class="truncate group-hover:text-inherit">
          <slot name="title" />
        </AppTitle>
        <!-- this inline-block removes the inherited text-decoration, since it cannot be simply overridden like any other parent css style -->
        <Caption class="inline-block">
          <slot name="description" />
        </Caption>
      </div>

      <div class="h-20 w-20 object-scale-down flex items-center justify-center">
        <slot name="image" />
      </div>
    </AppLink>
  </li>
</template>

// packages/blog/src/components/PostTiledList/Item.tsx
import {
  PublishedAtFormat,
  formatPostPublishedAt,
  getPostFullPath,
  type Post,
} from '@/shared/post.helpers';
import { cn } from '@/shared/react.helpers';
import { THEME } from '@/shared/theme';
import type { FunctionComponent } from 'react';
import { Caption } from '../Caption';
import { Link } from '../Link';
import { ThemedImage } from '../ThemedImage';
import { Title } from '../Title';

export const Item: ItemComponent = function ({ post, publishedAtFormat }) {
  return (
    <li
      className={cn(
        'flex flex-col p-3 text-medium rounded-md duration-100',
        'hover:border hover:shadow-md hover:scale-105',
        ...THEME.border,
      )}
      key={post.id}>
      <Link
        href={getPostFullPath(post)}
        prefetch="hover"
        className="flex items-center group">
        <div className="flex-1 overflow-hidden">
          <Title className={cn('truncate group-hover:text-inherit')}>
            {post.data.title}
          </Title>
          {/* this inline-block removes the inherited text-decoration, since it cannot be simply
          overridden like any other parent css style*/}
          <Caption className="inline-block">
            {formatPostPublishedAt(post, publishedAtFormat)}
          </Caption>
        </div>
        {post.data.coverImage && (
          <ThemedImage
            className="h-20 w-20 object-scale-down"
            src={post.data.coverImage.src}
            srcDark={post.data.coverImageDark?.src}
            alt={post.data.coverImageAlt!}
          />
        )}
      </Link>
    </li>
  );
};

export type ItemComponent = FunctionComponent<ItemProps>;

export interface ItemProps {
  post: Post;
  publishedAtFormat?: PublishedAtFormat;
}
