// packages/canvas/src/thoughts-on-modern-framework-features/ThoughtsOnModernFrameworkFeatures.vue
<script setup lang="ts">
import angularLogo from './angular-logo.png';
import reactLogo from './react-logo.svg';
import spiderManTriple from './spider-man-triple.jpg';
import vueLogo from './vue-logo.png';
import CenteredLayout from '@/shared/layouts/CenteredLayout.vue';
</script>

<template>
  <CenteredLayout>
    <div class="relative">
      <img :src="spiderManTriple" />

      <img
        class="absolute top-[160px] left-[70px] w-24 h-24"
        :src="vueLogo" />

      <img
        class="absolute top-[110px] left-[250px] w-24 h-24"
        :src="reactLogo" />

      <img
        class="absolute top-[165px] left-[400px] w-24 h-24"
        :src="angularLogo" />
    </div>
  </CenteredLayout>
</template>

// packages/canvas/src/ThoughtsOnModernFrameworkFeatures/ThoughtsOnModernFrameworkFeatures.tsx
import { Layout } from '@/shared/Layout.tsx';
import type { FunctionComponent } from 'react';
import angularLogo from './angular-logo.png';
import reactLogo from './react-logo.svg';
import spiderManTriple from './spider-man-triple.jpg';
import vueLogo from './vue-logo.png';

export const ThoughtsOnModernFrameworkFeatures: FunctionComponent =
  function () {
    return (
      <Layout>
        <div className="relative">
          <img
            src={spiderManTriple}
            alt=""
          />

          <img
            className="absolute top-[160px] left-[70px] w-24 h-24"
            src={vueLogo}
            alt=""
          />

          <img
            className="absolute top-[110px] left-[250px] w-24 h-24"
            src={reactLogo}
            alt=""
          />

          <img
            className="absolute top-[165px] left-[400px] w-24 h-24"
            src={angularLogo}
            alt=""
          />
        </div>
      </Layout>
    );
  };
